# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: MRC-group52
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: MRC-vol-back-1
    vol_size: 120
  - vol_name: MRC-vol-back-2
    vol_size: 120
  - vol_name: MRC-vol-back-3
    vol_size: 120
  # - vol_name: MRC-vol-front
  #   vol_size: 50

# Security group
security_groups:
  - name: mrc_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: mrc_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: backend-1
    volumes: ['MRC-vol-back-1']
  - name: backend-2
    volumes: ['MRC-vol-back-2']
  - name: backend-3
    volumes: ['MRC-vol-back-3']


