---
- name: Start a container with a couchdb
  become: true
  docker_container:
    name: "{{ couchdb_container_name}}"
    image: "{{ couchdb_image }}"
    ports:
      # 5984? Standard clustered port for all HTTP API requests
      - "5984:5984" 
      # Erlang port mapper daemon (epmd) ??
      - "4369:4369" 
      # Communication with other CouchDB nodes in the cluster. 
      # Single Erlang application on a machine, so range limited to a single port
      - "9100:9100" 
    volumes:
      - /data
    env:
      COUCHDB_PASSWORD: "{{ couchdb_password }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      NODENAME: "{{ inventory_hostname }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      