# This config file is for debug use!

app:

  # melb historical twitter json file from 2014-7 to 2017-6
  historical-tweet-file-path: /data/historical-tweets/twitter-melb.json
  covid-tweet-id-file-path: /data/covid-tweet-ids

  # for twitter streaming , select api version 1 or 2
  api-level: 2

  api-key: CFDfq0e0UVqwcBs5srwUYD06R
  api-secret: vpnAjv7uBf20TASxsWlH05iQEPzY58t2YnScNQ3WnUWxJbbhcf
  api-token: AAAAAAAAAAAAAAAAAAAAAJ6FbQEAAAAAWeRXYTv8SKSMt%2BkJzKajFeMSGBI%3DHxwsE6GOR3UXUhNGUbYf1YcgaR4lSsp0WQdpNpfLntpFfyt5jI
  access-token: 982640580512460801-JEhGJC0Oqmmuw8udB8knpfAVp7aMbky
  access-token-secret: 74AgO2bKazn4nFKnIsAU1a6GylXI6L42KdOiAVqlGzzMR

  # don't input to many
  # if key-word is an empty list, i.e. [], get all twitter
  key-word-list:
    - cat

  # 0~100, very loose to very strict match
  key-word-match-degree: 40

  is-fetch-english-tweet-only: yes

  target-db-name: test_db

  # melbourne place box
  target-box-points:
    - longitude: 144.59374
      latitude: -38.43385
    - longitude: 145.51252
      latitude: -37.51127



  db:
    username: admin
    password: 0F9YUJIgGoxIhgRWfHKS
    port: 5984
    host-list:
      - 161.117.88.132
#      - 127.0.0.1
#      - 127.0.0.1

  concurrency:
    block-queue-size: 512

