app:

  # 1 or 2
  api-level: 1

  api-key: CFDfq0e0UVqwcBs5srwUYD06R
  api-secret: vpnAjv7uBf20TASxsWlH05iQEPzY58t2YnScNQ3WnUWxJbbhcf
  api-token: AAAAAAAAAAAAAAAAAAAAAJ6FbQEAAAAAWeRXYTv8SKSMt%2BkJzKajFeMSGBI%3DHxwsE6GOR3UXUhNGUbYf1YcgaR4lSsp0WQdpNpfLntpFfyt5jI
  access-token: 982640580512460801-JEhGJC0Oqmmuw8udB8knpfAVp7aMbky
  access-token-secret: 74AgO2bKazn4nFKnIsAU1a6GylXI6L42KdOiAVqlGzzMR

  # don't input to many
  key-word-list:
    - COVID
    - Covid-19
    - Corona virus

  # 0~100, very loose to very strict match
  key-word-match-degree: 20

  target-db-name: coivd_lockdown_db
  # melbourne place box
  target-box-points:
    - longitude: 144.59374
      latitude: -38.43385
    - longitude: 145.51252
      latitude: -37.51127

  historical-tweet-file-path: /data/historical-tweets
  covid-tweet-id-file-path: /data/covid-tweet-ids


  is-fetch-english-tweet-only: true

  db:
    username: admin
    password: wQ104cwJ
    port: 5984
    host-list:
      - 127.0.0.1
#      - 127.0.0.1
#      - 127.0.0.1

  concurrency:
    block-queue-size: 512

