app:

  api-key: ErPfjMW8SOgGm4fsJL2buJQAa
  api-secret: Hg5cfLAVTVOJ9dFOtRXAHRX6Wi1mYzN4gOx29tMOqdyIjJs8pV
  api-token: AAAAAAAAAAAAAAAAAAAAAJ6FbQEAAAAAWeRXYTv8SKSMt%2BkJzKajFeMSGBI%3DHxwsE6GOR3UXUhNGUbYf1YcgaR4lSsp0WQdpNpfLntpFfyt5jI

  key-word-list:
    - lockdown
    - COVID
    - Covid-19
    - Corona virus
    - Coronavirus
    - melbournelockdown

  target-db-name: coivd_lockdown_db
  # great melbourne box
  target-box-points:
    -
        longtitude: 144.33363
        latitude: -38.50298
    -
        longtitude: 145.87841
        latitude: -37.17509


  is-fetch-english-tweet-only: true

  db:
    username: admin
    password: wQ104cwJ
    port: 5984
    host-list:
      - 127.0.0.1
      - 127.0.0.1
      - 127.0.0.1

  concurrency:
    block-queue-size: 512

