app:

  api-key: CFDfq0e0UVqwcBs5srwUYD06R
  api-secret: vpnAjv7uBf20TASxsWlH05iQEPzY58t2YnScNQ3WnUWxJbbhcf
  api-token: AAAAAAAAAAAAAAAAAAAAAJ6FbQEAAAAAWeRXYTv8SKSMt%2BkJzKajFeMSGBI%3DHxwsE6GOR3UXUhNGUbYf1YcgaR4lSsp0WQdpNpfLntpFfyt5jI
  access-token: 982640580512460801-JEhGJC0Oqmmuw8udB8knpfAVp7aMbky
  access-token-secret: 74AgO2bKazn4nFKnIsAU1a6GylXI6L42KdOiAVqlGzzMR

  key-word-list:
    - lockdown
    - COVID
    - Covid-19
    - Corona virus
    - Coronavirus
    - melbournelockdown

  target-db-name: coivd_lockdown_db
  # great melbourne box
  target-box-points:
    - longitude: 144.33363
      latitude: -38.50298
    - longitude: 145.87841
      latitude: -37.17509


  is-fetch-english-tweet-only: true

  db:
    username: admin
    password: wQ104cwJ
    port: 5984
    host-list:
      - 127.0.0.1
#      - 127.0.0.1
#      - 127.0.0.1

  concurrency:
    block-queue-size: 512

