app:

  # melb historical twitter json file from 2014-7 to 2017-6
  historical-tweet-file-path: /data/historical-tweets/twitter-melb.json
  covid-tweet-id-file-path: /data/covid-tweet-ids

  # for twitter streaming , select api version 1 or 2. Now 2 only.
  api-level: 2
  # is the api key has Academic Research access? true or false
  got-academic-access: false

#  api-key: CFDfq0e0UVqwcBs5srwUYD06R
#  api-secret: vpnAjv7uBf20TASxsWlH05iQEPzY58t2YnScNQ3WnUWxJbbhcf
#  api-token: AAAAAAAAAAAAAAAAAAAAAJ6FbQEAAAAAWeRXYTv8SKSMt%2BkJzKajFeMSGBI%3DHxwsE6GOR3UXUhNGUbYf1YcgaR4lSsp0WQdpNpfLntpFfyt5jI
#  access-token: 982640580512460801-JEhGJC0Oqmmuw8udB8knpfAVp7aMbky
#  access-token-secret: 74AgO2bKazn4nFKnIsAU1a6GylXI6L42KdOiAVqlGzzMR

#  api-key: bfa9kSteSfb1SXyVCfxfr1mWs
#  api-secret: bYwtGehL0L3eNremqAk0nBOcXurwRIGvLvfNjgcDh0FSVXn0y8
#  api-token: AAAAAAAAAAAAAAAAAAAAAMp1bgEAAAAAqWJoKo%2F7IgG7Z7%2FKIqr5i8ssApo%3DydM5w19XfscAuklgFz9bZzhaY7pB8m4y403KXEDAYWAG00AL2P
#  access-token: 1515881246039359488-lMhG3MeErJvfPqpfe0CG9qXGd8rksj
#  access-token-secret: kbeccnUWeo4ZuwKUhT47M08yWiRVcTmGiDJ7KMec0sAgQ

  api-key: QtnNzxVauOdQzGNPNxDq9NCnR
  api-secret: nWOV9xtcG9CSpIkgHULefqhMPpxI52pXxJc0O2E0xTqWvbA9lz
  api-token: AAAAAAAAAAAAAAAAAAAAAB2XbwEAAAAAN4MA38T7WhlpSKOhOR1b5kD7%2Fn0%3DJaU0jpBUCLR7F7DgHlZLh6RFqn1lQ6CeTwHoS1hnyzkO1p3HtC
  access-token: null
  access-token-secret: null

  # don't input to many
  # if key-word is an empty list, i.e. [], get all twitter
  key-word-list: []

  target-db-name: covid_search_debug_db

  # 0~100, very loose to very strict match
  key-word-match-degree: 40

  # true or false
  is-fetch-english-tweet-only: true

  # melbourne place box
  target-box-points:
    - longitude: 144.59374
      latitude: -38.43385
    - longitude: 145.51252
      latitude: -37.51127



  db:
    username: admin
    password: 0F9YUJIgGoxIhgRWfHKS
    port: 5984
    host-list:
      - 161.117.88.132
#      - 127.0.0.1
#      - 127.0.0.1

  concurrency:
    block-queue-size: 512

