app:
  demo-key: 123demo-value
  key-word-list:
    - lockdown
    - COVID
    - Covid-19
    - Corona virus
    - Coronavirus
    - melbournelockdown

  db:
    username: admin
    password: adm$n
    port: 5984
    host-list:
      - 321.321.321.321
      - 123.123.123.123
      - 233.233.233.233

