app:
  demo-key: 123demo-value

  db:
    username: admin
    password: admin
    # password: password
    # password: 0F9YUJIgGoxIhgRWfHKS
    port: 5984
    host-list:
      # local test
      # - 127.0.0.1
      # Xiao Tian test
      # - 161.117.88.132
      # MRC cluster
      - 172.26.128.63
      - 172.26.129.177
      - 172.26.134.100
    master-node:
      - 172.26.128.63


