app:
  demo-key: 123demo-value

  db:
    username: admin
    password: admin
    port: 5984
    host-list:
      # local test
      # - 127.0.0.1
      # MRC cluster
      - 172.26.128.63
<<<<<<< HEAD
      # - 172.26.134.211
      # - 172.26.133.48
    master-node:
      - 172.26.128.254
=======
      - 172.26.129.177
      - 172.26.134.100
    master-node: 172.26.128.63
    house-price-db: history_house_price_tweet_db
    covid-db: covid_search_tweet_mentioned_melb_db
    lockdown-db: covid_search_tweet_melb_jul_to_sep_2020_db
    stream-db: stream_debug_db
>>>>>>> 62d84b02069af2ff9b6a248844ff1ee45b013c8e


