# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: MRC-group52
instance_flavor: uom.mse.2c9g
host_ip_file: ./inventory/host_ip_file.ini # to store instances' ips

ansible_user: ubuntu
ansible_ssh_private_key_file: .ssh/MRC-group52.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Volume
volumes:
  - vol_name: MRC-vol-back-1
    vol_size: 120
  - vol_name: MRC-vol-back-2
    vol_size: 120
  - vol_name: MRC-vol-back-3
    vol_size: 120
  - vol_name: MRC-vol-front-1
    vol_size: 50

# Security group
security_groups:
  - name: mrc_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: mrc_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_http
    description: "CouchDB standard port"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_mapper
    description: "Erlang port mapper daemon (epmd)"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_comm
    description: "CouchDB cluster communication"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

# Instance
back_instances:
  - name: backend-1
    security_groups: ['mrc_ssh', 'mrc_http', 'couchdb_http', 'couchdb_mapper', 'couchdb_comm']
    volumes: ['MRC-vol-back-1']
  - name: backend-2
    security_groups: ['mrc_ssh', 'mrc_http', 'couchdb_http', 'couchdb_mapper', 'couchdb_comm']
    volumes: ['MRC-vol-back-2']
  - name: backend-3
    security_groups: ['mrc_ssh', 'mrc_http', 'couchdb_http', 'couchdb_mapper', 'couchdb_comm']
    volumes: ['MRC-vol-back-3']

front_instances:
  - name: frontend-1
    security_groups: ['mrc_ssh', 'mrc_http']
    volumes: ['MRC-vol-front-1']

git_dir: /data/COMP90024
git_user: ZRuizz
git_token: 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

