---
- name: git pull/clone
  #become: true
  git: 
    repo: https://{{git_token}}:@github.com/Blackmesa-Canteen/COMP90024-Cluster-and-Cloud-Computing-Assignment-2.git
    dest: /data/COMP90024/
    version: dev-frontend
    force: yes

# Install dependencies on the host
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: Use command to install npm n
  become: true
  ansible.builtin.shell:
    cmd: npm i -g n --force
    chdir: /data/COMP90024/frontend

- name: Use command to upgrade node
  become: true
  ansible.builtin.shell:
    cmd: n latest
    chdir: /data/COMP90024/frontend

- name: Use command to npm install
  become: true
  ansible.builtin.shell:
    cmd: npm install
    chdir: /data/COMP90024/frontend

- name: npm run build
  become: true
  ansible.builtin.shell:
    cmd: npm run build
    chdir: /data/COMP90024/frontend

# run docker compose for web app(include back/frond end)
- name: Create frontend directory
  become: true
  ansible.builtin.file:
    path: "{{ FRONTEND_PATH }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    #recurse: yes
    state: directory

- name: Create frontend build directory
  become: true
  ansible.builtin.file:
    path: "{{ FRONTEND_PATH }}/build"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    #recurse: yes
    state: directory

- name: generate nginx configuration
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ FRONTEND_PATH }}/nginx.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: generate dockerfile
  become: true
  ansible.builtin.template:
    src: dockerfile.j2
    dest: "{{ FRONTEND_PATH }}/Dockerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Stop a container with a command
  become: true
  community.docker.docker_container:
    name: frontend
    state: absent 

- name: Build an image
  become: true
  community.docker.docker_image:
    build:
      path: "{{FRONTEND_PATH}}"
    name: frontend
    #push: yes
    source: build
    force_source: yes

- name: Start a container with a command
  become: true
  community.docker.docker_container:
    name: frontend
    image: frontend
    detach: yes
    # restart: yes
    ports: 
      - "80:80"
    
