# create instances accroding to nectar.yaml
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  # to gether facts about the remote host(where this file is runned)
  gather_facts: true 
  roles: # in sequence
    - role: openstack-common
    #  - role: openstack-create-images # just for debug purposes
    - role: openstack-create-volume
    - role: openstack-create-security-group
    - role: openstack-create-instance
    

