---
# create CouchDB containers and run them
- hosts: backend
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true
  roles:
    - role: backend-create-docker-couchdb

# setup the CouchDB cluster
- hosts: masternode
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true
  roles:
    - role: backend-create-couchdb-cluster

# deploy backend applications
- hosts: backend
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true
  roles:
    - role: git-checkout-repo
    - role: deploy-backend
