---
- hosts: stream_crawler
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true

  roles:
    # - role: docker # duplicated. for test
    - role: git-checkout-repo
    - role: crawler-stream

- hosts: covid_search_crawler
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true

  roles:
    # - role: docker # duplicated. for test
    - role: git-checkout-repo
    - role: crawler-covid

- hosts: historical_crawler
  vars_files:
    - host_vars/backend.yaml
  gather_facts: true

  roles:
    # - role: docker # duplicated. for test
    - role: git-checkout-repo
    - role: crawler-historical
